services:
  - type: web
    name: ai-model
    env: python
    plan: free  
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CONFLUENCE_EMAIL
        sync: false
      - key: CONFLUENCE_API_TOKEN
        sync: false
      - key: PGVECTOR_CONNECTION
        sync: false
